{
 "title": "Envoy Service Health (HTTP)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "dc",
    "query": "label_values(consul_datacenter)"
   },
   {
    "name": "requester",
    "label": "requester (service)",
    "query": "label_values(envoy_cluster_upstream_rq_time_bucket{consul_datacenter=\"$dc\"},job)"
   },
   {
    "name": "upstream",
    "label": "upstream (service)",
    "query": "label_values(envoy_cluster_upstream_rq_time_bucket{consul_datacenter=\"$dc\"},envoy_cluster_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Upstream Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{consul_datacenter=~\"$dc\",envoy_response_code_class=~\"2\",envoy_cluster_name=~\"$upstream\",job=~\"$requester\"}[1m]))/\nsum(rate(envoy_cluster_upstream_rq_xx{consul_datacenter=~\"$dc\",job=~\"$requester\"}[1m]))",
     "legendFormat": "upstreams-HTTP2xx %"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{consul_datacenter=~\"$dc\",envoy_response_code_class=~\"4\",envoy_cluster_name=~\"$upstream\",job=~\"$requester\"}[1m]))/\nsum(rate(envoy_cluster_upstream_rq_xx{consul_datacenter=~\"$dc\",job=~\"$requester\"}[1m]))",
     "legendFormat": "upstreams-HTTP4XX %"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{consul_datacenter=~\"$dc\",envoy_response_code_class=~\"5\",envoy_cluster_name=~\"$upstream\",job=~\"$requester\"}[1m]))/\nsum(rate(envoy_cluster_upstream_rq_xx{consul_datacenter=~\"$dc\",job=~\"$requester\"}[1m]))",
     "legendFormat": "upstreams-HTTP5xx %"
    }
   ]
  },
  {
   "title": "Downstream Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=~\"2\",job=~\"$requester\"}[1m]))/\nsum(rate(envoy_http_downstream_rq_xx{job=~\"$requester\"}[1m]))",
     "legendFormat": "downstreams-HTTP2xx %"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=~\"4\",job=~\"$requester\"}[1m]))/\nsum(rate(envoy_http_downstream_rq_xx{job=~\"$requester\"}[1m]))",
     "legendFormat": "downstreams-HTTP4xx %"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=~\"5\",job=~\"$requester\"}[1m]))/\nsum(rate(envoy_http_downstream_rq_xx{job=~\"$requester\"}[1m]))",
     "legendFormat": "downstreams-HTTP5xx %"
    }
   ]
  },
  {
   "title": "Top Upstreams by Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, \n  sort_desc(\n    avg(rate(envoy_cluster_upstream_rq_time_sum{consul_datacenter=~\"$dc\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[5m])) by (job,envoy_cluster_name)/\n    avg(rate(envoy_cluster_upstream_rq_time_count{consul_datacenter=~\"$dc\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[5m])) by (job,envoy_cluster_name)\n  )\n)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Top Upstreams by 5xx",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(5,\n  sort_desc(\n    sum(\nrate(envoy_cluster_upstream_rq_xx{consul_datacenter=~\"$dc\",envoy_response_code_class=\"5\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[5m])) by (envoy_cluster_name)\n  )\n)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream HTTP500s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{consul_datacenter=\"$dc\",envoy_response_code=\"500\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[1m])) by (job,envoy_cluster_name)",
     "legendFormat": "{{job}}-->{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream HTTP502s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{consul_datacenter=\"$dc\",envoy_response_code=\"502\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[1m])) by (envoy_cluster_name,job)",
     "legendFormat": "{{job}}-->{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream HTTP503s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{consul_datacenter=\"$dc\",envoy_response_code=\"503\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[1m])) by (envoy_cluster_name,job)",
     "legendFormat": "{{job}}-->{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream HTTP504s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{consul_datacenter=\"$dc\",envoy_response_code=\"504\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[1m])) by (envoy_cluster_name,job)",
     "legendFormat": "{{job}}-->{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Downstream HTTP5xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\",job=~\"$requester\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Downstream Rq Resets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_rx_reset{job=~\"$requester\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request/sec By Upstream",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{consul_datacenter=~\"$dc\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[1m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg) By Upstream",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(envoy_cluster_upstream_rq_time_sum{consul_datacenter=~\"$dc\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[5m])) by (envoy_cluster_name)/\navg(rate(envoy_cluster_upstream_rq_time_count{consul_datacenter=~\"$dc\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[5m])) by (envoy_cluster_name)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Request Latency (p95) By Upstream",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_datacenter=~\"$dc\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[5m])) by (le, envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (p99) By Upstream",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_datacenter=~\"$dc\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[5m])) by (le, envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Connection Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_fail{consul_datacenter=~\"$dc\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[1m])) by (job,envoy_cluster_name)",
     "legendFormat": "{{job}}-{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Connection Timeouts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout{consul_datacenter=~\"$dc\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[1m])) by (job,envoy_cluster_name)",
     "legendFormat": "{{job}}-{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Envoy Health Check Network Failure to Services",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_health_check_network_failure{consul_datacenter=~\"$dc\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[1m])) by (job,envoy_cluster_name)",
     "legendFormat": "{{job}}-{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Failed Cluster Membership Updates",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_update_failure{consul_datacenter=~\"$dc\",job=~\"$requester\",envoy_cluster_name=~\"$upstream\"}[1m])) by (job,envoy_cluster_name)",
     "legendFormat": "{{flow_type}}-{{job}}-{{envoy_cluster_name}}"
    }
   ]
  }
 ]
}